# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='alpha',
            field=models.CharField(max_length=500),
        ),
    ]
