# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hang', '0002_auto_20160829_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Words',
        ),
    ]
